### PR TITLE
Use ManagedResource as Future

### PR DESCRIPTION
**Pull request by cchantep**
It may be useful to have a convinient function to use managed resource as `Future`.

### CODE REVIEW

**Comment by jsuereth** [comment]
I'm working on the 2.0 API now, so I can look into this now.

**Comment by cchantep** [comment]
Nice. Do not hesitate if I need to fix or rebase anything.

**Comment by jsuereth** [comment]
Alright, this looks great. I'll merge it as is, and then rebase my 2.0 on top of it.

FYI check out #37

**Comment by cchantep** [comment]
Thanks @jsuereth

**Pull request merged**
