### PR TITLE
Resource instance for releasable types

### PR DESCRIPTION
**Pull request by cchantep**
Structural instance of `Resource` for releasable type (having a `release()` method).

### CODE REVIEW

**Comment by jsuereth** [comment]
Hey, would mind rebasing this on changes to master now?

**Comment by cchantep** [comment]
updated

**Comment by cchantep** [comment]
@jsuereth is there any config issue with `travis-ci/push` ? The PR build seems ok.

**Comment by jsuereth** [comment]
@cchantep I think i broke master, slightly for the push build, going to work on fixing that.

**Pull request merged**
