### PR TITLE
Build for scala 2.12.0

### PR DESCRIPTION
**Pull request by allisonhb**
Add 2.12 to the build targets. It doesn't seem like anything else is needed. 

Would be nice as there are several projects that need a 2.12 binary of this. (it's useful~ :P)

Thanks!

### CODE REVIEW

**Comment by allisonhb** [comment]
Never mind, evidently travis dislikes 1.8.

**Comment by mtomko** [comment]
You can update the travis configuration to select java 1.8, but I'm not sure how to do it conditionally by scala version. For verification, it seems like it should be sufficient to test the 2.12 release with jdk8, though. The relevant line in the travis file is:

```yaml
# TODO - we'd like to actually test everything, but the process library has a deadlock right now
jdk:
  - oraclejdk7
```

**Comment by allisonhb** [comment]
Yeah, thanks! I've never actually used a travis project before (all jenkins), so that confused e until I noticed.

Anyhow, it seems to me that we run `test` and not `+test`, so it's not like we're running ci on all of the versions.

Thanks!!

**Comment by fester-io** [comment]
I can confirm that latest master works perfectly fine with 2.12.0. Won't post a PR, as I have just been very crude and removed all cross-compilation, changed version numbers and tried it. Compiles, tests all succeed and I tried 3 of the projects I use it in (thank you so much for ever creating it BTW); They are all well still too.

Thanks!! :-)

**Pull request closed without merging**
